title: "ESCRIME \\& CANCER DU SEIN"
lang: fr
author:
  - name: "Dr Philippe MICHEL"
    affiliations:
      name: "Hôpital NOVO"
      department: "Unité de Soutien à la Recherche Clinique"
format:
 titlepage-pdf:
  titlepage: bg-image
  titlepage-bg-image: "novo_usrc.png"
  logo-space-after: "0\\baselineskip"
  titlepage-include-file:
   - generique.tex
  documentclass: scrreprt
  number-sections: true
  titlepage-footer: "\\today"
titlepage-theme:
  title-fontstyle: ["Huge", "bfseries"]
  title-color: novo
  subtitle-color: novo
  subtitle-fontstyle: ["huge"]
  logo-size: "0.2\\textheight"
  vrule-width: "0.1cm"
  vrule-color: novo
include-in-header:
   file: entete.tex
df-print : kable
jss-pdf:
  keep-tex: true
pdf-engine: lualatex
keep-tex: true
number-sections: true
toc: true
lof: true
lot: true
fig-cap-location: bottom
tbl-cap-location: top
classoption: [french]
papersize: a4
editor: source
bibliography: stat.bib
cite-method: biblatex
csl: jama.csl
#reference-location: margin
#citation-location: margin
license: "MIT"
echo: false
warning: false
message: false


