> names(tt)
[1] "age"                      "temps_s1s20"              "chir"                    
[4] "gs_ca"                    "radiotherapie"            "chimio"                  
[7] "hormono"                  "meta"                     "distance_k"              
[10] "grabataire_sportive"      "pf_avant"                 "pf20seances"             
[13] "rp_avant"                 "rp20seances"              "bp_avant"                
[16] "bp20seances"              "gh_avant"                 "gh20seances"             
[19] "score_physique_avant"     "score_physique_20seances" "vt_avant"                
[22] "vt20seances"              "sf_avant"                 "sf20seances"             
[25] "re_avant"                 "re20seances"              "mh_avant"                
[28] "mh20seances"              "score_mental_avant"       "score_mental20seances" 